#!/bin/sh
brew cask install 1password\
brew cask install adobe-acrobat\
brew cask install adobe-photoshop-lightroom\
brew cask install alfred\
brew cask install amazon-drive\
brew cask install appcleaner\
brew cask install atext\
brew cask install bartender\
brew cask install caffeine\
brew cask install calibre\
brew cask install camtasia\
brew cask install carbon-copy-cloner\
brew cask install cheatsheet\
brew cask install chrome-remote-desktop-host\
brew cask install mkchromecast\
brew cask install cloudup\
brew cask install crashplan\
brew cask install daisydisk\
brew cask install dayone-cli\
brew cask install diskmaker-x\
brew cask install droidid\
brew cask install dropbox\
brew cask install droplr\
brew cask install duet\
brew cask install evernote\
brew cask install fantastical\
brew cask install firefox\
brew cask install titbit-connect\
brew cask install gemini\
brew cask install google-drive\
brew cask install google-earth\
brew cask install google-earth-pro\
brew cask install google-photos-backup\
brew cask install grammarly\
brew cask install i1profiler\
brew cask install hazel\
brew cask install lastpass\
brew cask install logitech-options\
brew cask install logmein-hamachi\
brew cask install malwarebytes-anti-malware\
brew cask install microsoft-office\
brew cask install mightytext\
brew cask install omnidisksweeper\
brew cask install omnifocus\
brew cask install overdrive-media-console\
brew cask install parallels-desktop\
brew cask install pdfpenpro\
brew cask install paragon-ntfs\
brew cask install private-internet-access\
brew cask install screens-connect\
brew cask install simplenote\
brew cask install skitch\
brew cask install skype\
brew cask install slack\
brew cask install sling\
brew cask install snagit\
brew cask install spotify\
brew cask install synology-cloud-station-backup\
brew cask install synology-cloud-station-drive\
brew cask install synology-photo-station-uploader\
brew cask install teamviewer\
brew cask install tunnelblick\
brew cask install viber\
brew cask install vlc\
brew cask install vox\
brew cask install WhatsApp\
brew cask install wordpresscom\
brew cask install yandex\
brew cask install zoomus\
